# This is the plugin.yml for the CraftyProfessions plugin. As you can see below
# this plugin does depend on Vault in order to distribute the money
# earned to a separate economy plugin.
name: CraftyProfessions
version: @VERSION@
description: This is a Professions plugin which will be completely customizable.
main: com.creedfreak.spigot.CraftyProfessionsSpigot
author: CreedTheFreak

depend: [Vault]
database: true

########################## Commands ########################
commands:
  prof:
    description: The entry point into the commands for CraftyProfessions
    usage: |
      Error False was returned from command!


  ### Random Commands for fun ###
  shower:
    description: The Shower Squad, That is all...
    usage: /<command>
    aliases: [shower, showersquad, showersqad, showersquad]


#################### Permissions ####################
#
# Input some sort of sassy description here
#
#
#
permissions:
  craftyprofessions.admin.*:
    default: op
    description: Give player all of the administration permissions

  craftyprofessions.use.*:
    default: op
    description: Give a player all of the use permissions

  craftyprofessions.db.*:
    default: op
    description: Give the player all of the database permissions
